config/routes.rb
Rails.application.routes.draw do
  get "render/index"
  resources :chat_clientes
  resources :usuarios
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "usuarios#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/chat_cliente.rb
class ChatCliente < ApplicationRecord
    validates :nm_cliente, presence: true
    validates :nr_cliente, presence: true
    validates :mensagem, presence: true
    validates :status_chat, inclusion: { in: [true, false] }
    validates :resposta_ia, presence: true
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    validates :nome, presence: true
    validates :numero, presence: true
    validates :tipo_de_envio, inclusion: { in: [true, false] }
    validates :email, presence: true
    validates :senha, presence: true
    validates :descricao, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/chat_clientes_controller.rb
class ChatClientesController < ApplicationController
  before_action :set_chat_cliente, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /chat_clientes or /chat_clientes.json
  def index
    @chat_clientes = ChatCliente.all
  end

  # GET /chat_clientes/1 or /chat_clientes/1.json
  def show
  end

  # GET /chat_clientes/new
  def new
    @chat_cliente = ChatCliente.new
  end

  # GET /chat_clientes/1/edit
  def edit
  end

  # POST /chat_clientes or /chat_clientes.json
  def create
    @chat_cliente = ChatCliente.new(chat_cliente_params)

    respond_to do |format|
      if @chat_cliente.save
        format.html { redirect_to @chat_cliente, notice: "Chat cliente was successfully created." }
        format.json { render :show, status: :created, location: @chat_cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chat_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chat_clientes/1 or /chat_clientes/1.json
  def update
    respond_to do |format|
      if @chat_cliente.update(chat_cliente_params)
        format.html { redirect_to @chat_cliente, notice: "Chat cliente was successfully updated." }
        format.json { render :show, status: :ok, location: @chat_cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chat_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chat_clientes/1 or /chat_clientes/1.json
  def destroy
    @chat_cliente.destroy!

    respond_to do |format|
      format.html { redirect_to chat_clientes_path, status: :see_other, notice: "Chat cliente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat_cliente
      @chat_cliente = ChatCliente.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def chat_cliente_params
      params.expect(chat_cliente: [ :nm_cliente, :nr_cliente, :mensagem, :status_chat, :resposta_ia ])
    end
end

app/controllers/render_controller.rb
class RenderController < ApplicationController
  def index
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
    respond_to do |format|
      format.html
      format.json { render json: @usuarios }
    end
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_usuario
    @usuario = Usuario.find(params[:id])
  end

  def usuario_params
    params.require(:usuario).permit(:nome, :numero, :tipo_de_envio, :email, :senha, :descricao)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_clientes_helper.rb
module ChatClientesHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/render_helper.rb
module RenderHelper
end

app/helpers/usuario_helper.rb
module UsuarioHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/chat_clientes/_chat_cliente.html.erb
<div id="<%= dom_id chat_cliente %>">
  <p>
    <strong>Nm cliente:</strong>
    <%= chat_cliente.nm_cliente %>
  </p>

  <p>
    <strong>Nr cliente:</strong>
    <%= chat_cliente.nr_cliente %>
  </p>

  <p>
    <strong>Mensagem:</strong>
    <%= chat_cliente.mensagem %>
  </p>

  <p>
    <strong>Status chat:</strong>
    <%= chat_cliente.status_chat %>
  </p>

  <p>
    <strong>Resposta ia:</strong>
    <%= chat_cliente.resposta_ia %>
  </p>

</div>

app/views/chat_clientes/_form.html.erb
<%= form_with(model: chat_cliente) do |form| %>
  <% if chat_cliente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chat_cliente.errors.count, "error") %> prohibited this chat_cliente from being saved:</h2>

      <ul>
        <% chat_cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nm_cliente, style: "display: block" %>
    <%= form.text_field :nm_cliente %>
  </div>

  <div>
    <%= form.label :nr_cliente, style: "display: block" %>
    <%= form.text_field :nr_cliente %>
  </div>

  <div>
    <%= form.label :mensagem, style: "display: block" %>
    <%= form.text_field :mensagem %>
  </div>

  <div>
    <%= form.label :status_chat, style: "display: block" %>
    <%= form.checkbox :status_chat %>
  </div>

  <div>
    <%= form.label :resposta_ia, style: "display: block" %>
    <%= form.text_field :resposta_ia %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chat_clientes/edit.html.erb
<% content_for :title, "Editing chat cliente" %>

<h1>Editing chat cliente</h1>

<%= render "form", chat_cliente: @chat_cliente %>

<br>

<div>
  <%= link_to "Show this chat cliente", @chat_cliente %> |
  <%= link_to "Back to chat clientes", chat_clientes_path %>
</div>

app/views/chat_clientes/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Chat clientes" %>

<h1>Chat clientes</h1>

<div id="chat_clientes">
  <% @chat_clientes.each do |chat_cliente| %>
    <%= render chat_cliente %>
    <p>
      <%= link_to "Show this chat cliente", chat_cliente %>
    </p>
  <% end %>
</div>

<%= link_to "New chat cliente", new_chat_cliente_path %>

app/views/chat_clientes/new.html.erb
<% content_for :title, "New chat cliente" %>

<h1>New chat cliente</h1>

<%= render "form", chat_cliente: @chat_cliente %>

<br>

<div>
  <%= link_to "Back to chat clientes", chat_clientes_path %>
</div>

app/views/chat_clientes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @chat_cliente %>

<div>
  <%= link_to "Edit this chat cliente", edit_chat_cliente_path(@chat_cliente) %> |
  <%= link_to "Back to chat clientes", chat_clientes_path %>

  <%= button_to "Destroy this chat cliente", @chat_cliente, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Store" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/render/index.html.erb
<h1>Render#index</h1>
<p>Find me in app/views/render/index.html.erb</p>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario) do |form| %>
  <% if usuario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :numero, style: "display: block" %>
    <%= form.text_field :numero %>
  </div>

  <div>
    <%= form.label :tipo_de_envio, style: "display: block" %>
    <%= form.checkbox :tipo_de_envio %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/_usuario.html.erb
<div id="<%= dom_id usuario %>">
  <p>
    <strong>Nome:</strong>
    <%= usuario.nome %>
  </p>

  <p>
    <strong>Numero:</strong>
    <%= usuario.numero %>
  </p>

  <p>
    <strong>Tipo de envio:</strong>
    <%= usuario.tipo_de_envio %>
  </p>

</div>

app/views/usuarios/edit.html.erb
<% content_for :title, "Editing usuario" %>

<h1>Editing usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Show this usuario", @usuario %> |
  <%= link_to "Back to usuarios", usuarios_path %>
</div>

app/views/usuarios/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Usuarios" %>

<h1>Usuarios</h1>

<div id="usuarios">
  <% @usuarios.each do |usuario| %>
    <%= render usuario %>
    <p>
      <%= link_to "Show this usuario", usuario %>
    </p>
  <% end %>
</div>

<%= link_to "New usuario", new_usuario_path %>

app/views/usuarios/new.html.erb
<% content_for :title, "New usuario" %>

<h1>New usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Back to usuarios", usuarios_path %>
</div>

app/views/usuarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @usuario %>

<div>
  <%= link_to "Edit this usuario", edit_usuario_path(@usuario) %> |
  <%= link_to "Back to usuarios", usuarios_path %>

  <%= button_to "Destroy this usuario", @usuario, method: :delete %>
</div>